### ISSUE TITLE
More pixels.

### ISSUE THREAD

**Issue by rsilvers129** [Hans2004/AnyCubic-Photon-Decrease-Pixel#1]
https://docs.google.com/spreadsheets/d/1yDwszgncTyOxvyJho6y1kxLJquH2GsfL83KaFXT6068/edit#gid=0

Sometimes 2 or 3 pixels are needed. So maybe the command-line should allow you to specify 1, 2, or 3.

**Comment by Hans2004** [comment]
I will adapt the code for more pixels when I find the time. In the meantime you can just run the program again on the file that was put out the first time if you want to decrease by two pixels.
