### ISSUE TITLE
Kudos?

### ISSUE THREAD

**Issue by X3msnake** [Hans2004/AnyCubic-Photon-Decrease-Pixel#3]
where are the refereces to the sources you used for this. dont tell me you reversed the photon format all by yourself because you didnt :)

**Comment by Hans2004** [comment]
No, I did not reverse the .photon format all by myself. I looked at this program: https://github.com/Photonsters/PhotonFileEditor

It still took me quite a bit of effort to understand that code because I am not a Python programmer. So, perhaps still worth a mini kudo's.  ;P
